services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ETCD_CLIENT_URL: http://etcd:2379
    ports:
      - "8989:8989"
    volumes:
      - ./:/app:delegated
    depends_on:
      - etcd
      - vault

  etcd:
    container_name: etcd
    image: bitnami/etcd:3.5.9
    restart: always
    ports:
     - "12379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - LISTEN_CLIENT_URLS=http://etcd:2379

  vault:
    image: vault:1.13.3
    container_name: vault
    restart: on-failure:10
    ports:
      - "8201:8201"
    cap_add:
      - IPC_LOCK
    healthcheck:
      retries: 5
    environment:
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8201"
      VAULT_DEV_ROOT_TOKEN_ID:  "myroot"
