services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ETCD_CLIENT_URL: http://etcd:2379
    ports:
      - "8989:8989"
    volumes:
      - ./:/app:delegated
    depends_on:
      - etcd

  etcd:
    container_name: etcd
    image: bitnami/etcd:3.5.9
    restart: always
    ports:
     - "12379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - LISTEN_CLIENT_URLS=http://etcd:2379
